$engine: 3
name: S-ESX
version: 2.1.0
author: Schwim & ESX Team
description: A full featured (13 jobs) and highly configurable yet lightweight ESX v1-final base that can be easily extended. 

tasks:
 
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/S-ESX/S-ESX-V1F/
    ref:  master
    dest: ./tmp/s-esx

  - action: move_path
    src: ./tmp/s-esx/server.cfg
    dest: ./server.cfg
  
  - action: move_path
    src: ./tmp/s-esx/resources
    dest: ./resources

  - action: connect_database
  - action: query_database
    file: ./tmp/s-esx/sesx.sql

  - action: remove_path
    path: ./tmp